"""Renders a report as a professional PDF — the same real evidence-cited content
``_render_report_markdown`` (services.py) produces, laid out with fpdf2 instead of Markdown.

fpdf2 (not a headless-browser/HTML-to-PDF pipeline) is a deliberate choice: this image is already
CPU-only and deliberately lean (see apps/api/Dockerfile's own comment on trimming the torch
install) — fpdf2 is pure Python with no system library dependencies (no Chromium, no
Pango/Cairo), so this feature adds zero build-time or image-size cost. The trade is imperative
layout code instead of CSS/Markdown, a fine trade for a document with this few, this well-known
section shapes.
"""

from __future__ import annotations

from datetime import datetime

from fpdf import FPDF

from auditmind_api.reporting.domain.entities import Finding, FindingEvidence, FindingSeverity

_SEVERITY_ORDER: dict[FindingSeverity, int] = {
    FindingSeverity.CRITICAL: 0,
    FindingSeverity.HIGH: 1,
    FindingSeverity.MEDIUM: 2,
    FindingSeverity.LOW: 3,
}

# The same severity/ink tokens as globals.css, hand-mirrored here since a PDF renderer can't read
# a CSS custom property — see that file's `--risk-*`/`--ink*` definitions for the source of truth.
_SEVERITY_COLOR: dict[FindingSeverity, tuple[int, int, int]] = {
    FindingSeverity.CRITICAL: (217, 48, 37),
    FindingSeverity.HIGH: (184, 134, 11),
    FindingSeverity.MEDIUM: (184, 134, 11),
    FindingSeverity.LOW: (26, 127, 55),
}
_INK = (13, 13, 13)
_INK_SECONDARY = (90, 90, 105)
_INK_MUTED = (130, 130, 145)
_LINE = (229, 229, 229)
_WARN_BG = (251, 243, 221)
_WARN_TEXT = (140, 100, 8)

# fpdf2's core (Helvetica/Times/Courier) fonts only render WinAnsi (cp1252) — every citation,
# description, or disposition reason is free-form user/AI text that may contain a real Unicode
# character (a curly quote, an em dash) those fonts can't draw. Substituting the closest ASCII
# equivalent is safer than letting a whole export fail on the one document a reviewer needs.
_UNSAFE_CHARS = {
    "—": "-",
    "–": "-",
    "‘": "'",
    "’": "'",
    "“": '"',
    "”": '"',
    "…": "...",
}


def _safe(text: str) -> str:
    for bad, good in _UNSAFE_CHARS.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", "replace").decode("latin-1")


class _ReportPDF(FPDF):
    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*_INK_MUTED)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def render_report_pdf(
    *,
    version: int,
    generated_by: str,
    generated_at: datetime,
    findings: list[Finding],
    evidence_by_finding: dict[str, list[FindingEvidence]],
) -> bytes:
    """Mirrors ``_render_report_markdown``'s content exactly — same sort order, same "none
    attached" honesty for a finding with no citations, same evidence-per-citation shape — laid
    out as a PDF instead of Markdown. Both functions read the same ``findings``/
    ``evidence_by_finding`` inputs ``generate_report()`` already assembles, so there is exactly one
    place a report's actual content comes from regardless of which format a reader asks for.
    """
    pdf = _ReportPDF(format="letter")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(20, 18, 20)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 10, "Audit Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*_INK_SECONDARY)
    pdf.cell(0, 6, _safe(f"Version {version}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, _safe(f"Generated by {generated_by}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(
        0,
        6,
        _safe(f"Generated at {generated_at.strftime('%Y-%m-%d %H:%M UTC')}"),
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf.ln(2)
    pdf.set_draw_color(*_LINE)
    pdf.line(20, pdf.get_y(), pdf.w - 20, pdf.get_y())
    pdf.ln(6)

    ordered = sorted(findings, key=lambda f: (_SEVERITY_ORDER[f.severity], f.title))

    if not ordered:
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(*_INK_SECONDARY)
        pdf.multi_cell(
            0,
            6,
            "No findings had been confirmed for this engagement at the time this report was "
            "generated.",
        )
        return bytes(pdf.output())

    counts: dict[FindingSeverity, int] = {s: 0 for s in FindingSeverity}
    for f in ordered:
        counts[f.severity] += 1
    summary = ", ".join(f"{counts[s]} {s.value}" for s in _SEVERITY_ORDER if counts[s] > 0)

    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*_INK)
    pdf.cell(0, 8, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*_INK_SECONDARY)
    pdf.multi_cell(0, 6, _safe(f"{len(ordered)} confirmed finding(s) - {summary}."))
    pdf.ln(4)

    for finding in ordered:
        color = _SEVERITY_COLOR[finding.severity]

        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*color)
        pdf.cell(0, 5, _safe(finding.severity.value.upper()), new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(*_INK)
        pdf.multi_cell(0, 7, _safe(finding.title))

        meta = f"Status: {finding.status.value}"
        if finding.control_id:
            meta += f"  |  Control: {finding.control_id}"
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*_INK_MUTED)
        pdf.cell(0, 5, _safe(meta), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        pdf.set_font("Helvetica", "", 10.5)
        pdf.set_text_color(*_INK_SECONDARY)
        pdf.multi_cell(0, 5.5, _safe(finding.description))
        pdf.ln(1.5)

        evidence = evidence_by_finding.get(finding.id, [])
        if evidence:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*_INK_MUTED)
            word = "citation" if len(evidence) == 1 else "citations"
            pdf.cell(
                0, 5, _safe(f"EVIDENCE ({len(evidence)} {word})"), new_x="LMARGIN", new_y="NEXT"
            )
            for item in evidence:
                y_before = pdf.get_y()
                pdf.set_x(pdf.l_margin + 4)
                pdf.set_font("Helvetica", "I", 9.5)
                pdf.set_text_color(*_INK_SECONDARY)
                pdf.multi_cell(pdf.epw - 4, 5, _safe(item.citation_text))
                pdf.set_x(pdf.l_margin + 4)
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*_INK_MUTED)
                pdf.cell(
                    0,
                    4.5,
                    _safe(f"- source chunk {item.chunk_id[:8]}"),
                    new_x="LMARGIN",
                    new_y="NEXT",
                )
                # A thin left rule beside the quote — the same "evidence reads as a distinct
                # citation, not prose" treatment the in-app report view uses.
                pdf.set_draw_color(*_LINE)
                pdf.line(pdf.l_margin, y_before, pdf.l_margin, pdf.get_y())
                pdf.ln(2)
        else:
            pdf.set_fill_color(*_WARN_BG)
            pdf.set_text_color(*_WARN_TEXT)
            pdf.set_font("Helvetica", "", 9.5)
            pdf.multi_cell(
                0,
                6,
                "No evidence attached - this finding is not yet supported by cited source "
                "evidence.",
                fill=True,
            )
        pdf.ln(5)

    return bytes(pdf.output())
