import asyncio
import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Importing the models module registers this service's `agent.*` tables onto the shared metadata
# below as a side effect of the import — SQLAlchemy tables only appear on `Base.metadata` once
# their module has actually executed. This is the only context this service has, so it is the only
# import here (unlike apps/api's env.py, which lists one per bounded context).
import agent_orchestrator.infrastructure.models  # noqa: F401
from agent_orchestrator.infrastructure.orm_base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# See `do_run_migrations`'s comment: this service's migration history must not collide with
# apps/api's in the shared physical database.
_VERSION_TABLE = "agent_orchestrator_alembic_version"

# Migrations run as a privileged/admin database role — never the least-privilege `auditmind_app`
# role the running service connects as (shared/database.py) — because creating schemas and RLS
# policies requires elevated grants the service itself must never hold (Phase 11 §7/§8). Read from
# this service's own migration env var, separate from apps/api's, so the two services' migration
# credentials are configured independently even against the same database.
migration_url = os.environ.get("AGENT_MIGRATION_DATABASE_URL")
if migration_url:
    config.set_main_option("sqlalchemy.url", migration_url)


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        version_table=_VERSION_TABLE,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    # `include_schemas=True` is required because this service's tables live in the non-`public`
    # `agent` schema and FK into `identity` — without it, autogenerate's reflection only sees the
    # connection's default schema and mis-diffs cross-schema tables. Same reasoning apps/api's
    # env.py documents (Increment 04). Autogenerated diffs must still always be reviewed by hand.
    #
    # `version_table` is set to a name distinct from apps/api's default `alembic_version` — the
    # two services share one physical Postgres database (Phase 4 §1) but each owns an independent
    # migration history (ADR-001, separate deployables). Without this, both alembic contexts would
    # write to the same `public.alembic_version` row and each service's `upgrade head` would try to
    # resolve the *other* service's revision id, exactly the "Can't locate revision" failure this
    # was added after hitting for real against the shared dev database.
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_schemas=True,
        version_table=_VERSION_TABLE,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
